global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#igor-leontev'
