version: '3.3'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:1.0
    ports:
      - 9292:9292/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:1.0
    networks:
      back_net:
        aliases:
          - post_db
      front_net:
        aliases:
          - post_db
  comment:
    build: ./ui
    image: ${USERNAME}/comment:1.0
    networks:
      back_net:
        aliases:
          - comment_db
      front_net:
        aliases:
          - comment_db
volumes:
  post_db:

networks:
  front_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.1.0/24
  back_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.2.0/24
