version: '3.3'
services:
  mongo_db:
    image: mongo:${MONGO_VER}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${EXTERNAL_PORT}:${CONTAINER_PORT}/${PROTOCOL}
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      back_net:
        aliases:
          - post_db
      front_net:
        aliases:
          - post_db
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      back_net:
        aliases:
          - comment_db
      front_net:
        aliases:
          - comment_db
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      back_net:
        aliases:
          - prometheus
      front_net:
        aliases:
          - prometheus

volumes:
  post_db:

networks:
  front_net:
    driver: bridge
    ipam:
      config:
      - subnet: ${FRONT_SUBNET}
  back_net:
    driver: bridge
    ipam:
      config:
      - subnet: ${BACK_SUBNET}
