dependencies:
  - name: ui
    version: "1.0.0"
    repository: file://../ui
  - name: post
    version: 1.0.0
    repository: file://../post
  - name: comment
    version: 1.0.0
    repository: file://../comment
